import numpy as np 
import json

def process_clickset(click_set_dict, version_param):
    
    supported_version_params = ['1']

    #Processes the initialisation click set generated by AddInitialSeedsMissingLabelsd type transform. This produces a dict of nested lists, with points that have length
    #N + 1. The latter N are spatial dimensions in RAS, while the first is a value which can be used to determine whether the click is valid or not. 

    #If any value in a point sublist is -1, then invalid click and discard. 

    processed_click_set = dict() 

    for class_label, points_list in click_set_dict.items():

        #If the points list is not a list datatype but is a string of a nested list, or a numpy array of a nested list:
        points_list = points_list.tolist() if isinstance(points_list, np.ndarray) else points_list
        points_list = json.loads(points_list) if isinstance(points_list, str) else points_list

        new_points_list = []
        for point in points_list:
            if any([i < 0 for i in point]): #This eradicates any non-valid points generated in the initialisation/editing.
                continue
            else:
                #Then we discard the first value, to get left with the point coordinate in RAS.
                new_points_list.append(point[1:])
        
        processed_click_set[class_label] = new_points_list
    
    #We assert that the click set should have at least one click across the classes.
    if sum([len(sublist) for sublist in list(processed_click_set.values())]) < 1:
        raise ValueError('The click set requires at least one click across the classes for initialisation.')

    return processed_click_set

# def process_edit_clickset(click_set_dict, version_param):

#     supported_version_params = ['1']
#     assert version_param in supported_version_params:

#     if version_param == '1':
#     #Processes the edit click set generated by the addrandomguidanced type transform. This transform generates a dict of nested lists, with points that have length 4.
#     # The latter three are spatial dimensions in RAS, while the first is a value which can be used to determine whether the click is valid or not.
#     # 
#     # IF any value in a point sublist is -1 then invalid click and discard.
#     # 
#     # Then we discard the first value to get left with the point coordinate in RAS. 

#     return
